### ISSUE TITLE
浏览器侧需要反映 SSH 连接的部分情况。

### ISSUE THREAD

**Issue by LamGC** [Yorlg/WebSSH#4]
在 SSH 连接过程中会出现一些情况，网页需要对这些情况做出反映（比如弹出提示框）：
- SSH 连接失败 - 认证失败；
- SSH 连接失败 - 网络原因
- 与 WebSSH 后端的连接丢失
  - 进行重连
  - 无法重连
- SSH 已结束（用户登出）（可能要检测 SSH 状态？）

**Comment by Yorlg** [comment]
目前确实少了错误提示，下个版本加上。
